CFLAGS= -Wall -pedantic-errors

all: gtushell bunedu pwd lsf cat wc

gtushell:
	gcc $(CFLAGS) gtushell.c -o gtushell

bunedu:
	gcc $(CFLAGS) buNeDu.c -o bunedu

pwd:
	gcc $(CFLAGS) pwd.c -o pwd

lsf:
	gcc $(CFLAGS) lsf.c -o lsf

cat:
	gcc $(CFLAGS) cat.c -o cat

wc:
	gcc $(CFLAGS) wc.c -o wc

clean:
	rm gtushell bunedu pwd lsf cat wc